version: '3.9'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env  # Specify the path to your .env file
  db:
    image: postgres:14.1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=open-flights
      - POSTGRES_PASSWORD=open-flights
      - POSTGRES_DB=open-flights_development
