version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://devops_user:devops_password@db:5432/devops_development
    volumes:
      - .:/app
  
  db:
    image: postgres:14.11
    environment:
      POSTGRES_DB: devops_development
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
    ports:
      - "5432:5432"
