default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "devops_user" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "devops_password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "devops_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "devops_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "devops_production" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "devops_user" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "devops_password" } %>
